### ISSUE TITLE
Joy Stick not move on mobile device

### ISSUE THREAD

**Issue by yukebrillianth** [rockyfrank/rc-joystick#6]
[Screencast from 28-11-24 22:41:58.webm](https://github.com/user-attachments/assets/a419d979-ff57-4266-baf9-7039f28b83c4)

**Comment by rockyfrank** [comment]
Sorry, just saw this.
Chrome's devtool does not trigger re-rendering when switching devices, so the environment information obtained directly from UA at the beginning is incorrect after switching devices. In theory, you can refresh the browser after switching to the mobile view to make it works. However, I have changed the logic in v1.0.5 to determine the environment at runtime, so this problem has been fixed.
